---
title: "R Generation article - Discussion"
author: "Shamindra Shrotriya"
date: '2018-08-16'
slug: r-generation-article-discussion
categories: ["CMU"]
tags: []
excerpt: "comment"
---

# Background

This week in our [CMU History of Statistics Group](http://www.stat.cmu.edu/~lrichard/history-of-stats/history-of-stats.html) 
we are discussing the article [R Generation](https://rss.onlinelibrary.wiley.com/doi/epdf/10.1111/j.1740-9713.2018.01169.x) 
from the quarterly Significance Magazine by the American Statistical Association.

Each week in the group we find a great article celebrating some big idea in 
the history of statistics and just have an informal group discussion on what 
those ideas mean to us today as practicing and research statisticians...sorry 
data scientists.

(Put in a note here about how we live in an amazing statistical time and due to perfect storm, and sometimes it is useful to sit and reflect on the past, present
and future...)
We picked this article as our beloved `R` language celebrates is 25th anniversary
`r emo::ji("birthday")` of it's first public release since. Given how critically
important statistical computing is to our work and research and increasingly so
given the perfect storm of improved high-performance hardware, cheaper cloud
data storage and the open access to high quality statistical software including
`R` it seemed like the perfect time to veer our discussions into reflecting on
the past and our thoughts for it's future and in the process, ours `r emo::ji("smile")`.

# Summary of Article

The article offers a concise perspective on the phenomenon that is `R` and is organized
in 4 main parts namely `R`'s History, `R` Community, `R` Culture and `R` Future. Below we note some of the 
interesting points for each section for the discussion.

## `R`'s History

- August 2018 marks the 25th anniversary of `R`
- The origin of `R` is formed by the collaboration of Ross Ihaka (University of 
Auckland) and Robert Gentleman (University of Waterloo) who met when Gentleman
was visited the Auckland campus in 1992
- They wanted to develop a language as flexible as `Scheme` but with the added
statistical functionality and syntax of the existing `S` language
- Over the span of 3 months they developed the first version of what would be
the `R` language - a fun nod to the first letter of both the authors first names
- It was adopted by the university of Auckland who needed statistical software
that worked on Macintosh - talk about being cross platform from the get go!
- They released it publicly on the `S` listserv mailing list in August 1993
- In mid-90's they considered turning it into a commercial product, but were
luckily swayed away to keep it open access by fellow core member Martin Machler from ETH - phew!`r emo::ji("phew")`.

### Discussion Questions:

- Any other interesting `R` historical anecdotes that people want to share?
- Were there any promising competitors to `R` that went from open-source to
closed-source and lost popularity?

- AR: Lispstat. Was famous because it had a lot of interactive features in the 90s. Make a graph, have buttons and sliders.
- Basically interactive 'applets' before applets had been invented
- Was quite big in UCLA (Jan de Lew). Went into a quick decline was 
a very lispy syntax
- Led to things like parentheses are faster than curly braces
- S was big enough before R, so by adapting to it's syntax R presumably
became more popular than other open source counterparts
- Article should talk about the contributions of `S` and John Chambers
is involved

- Article jumps from `CRAN` directly to modern contributions such as the tidyverse. Other developments could have been mentioned. Hadley Wickham
- AR filed a bug report in 2014 which still hasn't been fixed yet.
- `CRAN` was the best way to package things at the time. It centralized
package management
- Getting stuff on CRAN is quite challenging but this is expected for
more rigorous quality control, alternative is launch via github using `devtools`
- Is the `CRAN` peer review standard outdated now?
- Ron: Is the Journal of Statistical Software a higher bar than loading
a package on `CRAN`? AR: Yes
- Who will the `R Core` team pass on their duties to?
- LR: Should we be teaching the tidyverse to beginners? Makes it difficult to transition to `Python` which has lower level data structures. 
- Syntax of `stringr` is really useful
- PE: Feeling of everything is a nail, use the hammer. Dataframes may
not always be the best tool for the job

## `R`'s Community

- By mid-1997 the R Core team had 11 members including the original authors
- In March 1997 the biggest breakthrough occurred - Kurt Hornik and Friedrich
Leisch developed `CRAN`
- `CRAN` meant that all libraries and `R` files were freely available in one place
- Importantly this open access meant that the original `R Core` community began
to extend to wider data science community via the development of specific libaries!
- Enter Hadley Wickham, who helped launch some of the most widely used packages
including `dplyr` and `ggplot2` (part of his thesis!)
- This set of packages often wrap existing base `R` functionality in a very 
clear API
- Ultimately this has minimized barriers of entry to using `R` by non CS
users and encouraged entry from users in diverse fields such as life sciences
and humanities
- LR: Hadley's greatest package is `devtools`. TP: This has led to an
explosion in the number of packages used.

## `R` Culture

- `R` has traditionally been very male dominated
- Gabriela de Queiroz and other users have sought to make the community more
diverse
- In October 2012 de Queiroz founded the ï¬rst chapter of R-Ladies in San Francisco to encourage women and others could:

> feel comfortable asking questions and making suggestions. 

- Today there are 64 chapters and 13000 members around the world and growing!
- Diveristy of representation is improving slowly, the percentage of invited 
useR! conference talks by women increased from 0 to 34% from 2004 to 2016
- AR: RCatladies. RY: Compared to other languages it is likely better
in terms of representation.

### Discussion Questions:

- Has anybody had any good personal experiences with RLadies they would like to
share?
- What are some of the diversity efforts we are leading at CMU - specific to `R`
or just in general?

## `R` Future

### Discussion Questions:

- Thomas Lumley feels that another statistical computing language won't replace
`R` soon
- Lumley feels that such a language would need to absorb `CRAN` and it's
stockpile of code
- `CRAN` currently holds more than 12000 packages and 'is growing near-exponentially'. Interestingly the article notes that:

> From January to May 2018, a median of 21 packages were added or updated per day. 

- One solution to sustain `CRAN` is simply to add more reviewers


- What is the impact of `R` (and `Python`) long term on closed source 
competitors such as `SAS` and `Matlab`
- How do people think `CRAN` review quality can be sustained to the standard
that it is now?
- Should `R` have a set of standards like `PEP8` for preferred coding practices
that can be statically checked before submitting packages? We have some of these
already via `R CMD CHECK` and also 
- What are the key limitations in `R` that people would like to see resolved
e.g. new native data structures at the core level?
- Taylor - can you describe the N-language problem and ways that we
are addressing this? 
- What role do students think of `Julia` as a leading statistical computing platform?
- Are we going to focus statistical computing courses on `Julia` more
now that it is stabilized?